port: 7890
socks-port: 7891
mixed-port: 7897
external-controller: 127.0.0.1:9090
allow-lan: true
bind-address: "*"
mode: rule
log-level: warning
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true
unified-delay: true
tcp-concurrent: true

dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - system
  nameserver:
    - system
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.arpa"
    - "time.*.com"
    - "ntp.*.com"

tun:
  enable: false
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

proxy-providers:
  Kuromis:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: DIRECT

proxy-groups:
  - { name: PROXY, type: select, proxies: [🇭🇰 香港, 🇹🇼 台湾, 🇺🇳 其他, DIRECT] }
  - { name: AD, type: select, proxies: [PROXY, DIRECT, REJECT] }
  - {
      name: 🇭🇰 香港,
      type: fallback,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?i)(港|hong|hk)",
    }
  - {
      name: 🇹🇼 台湾,
      type: fallback,
      include-all: true,
      tolerance: 20,
      interval: 300,
      filter: "(?i)(台|tai|tw)",
    }
  - {
      name: 🇺🇳 其他,
      type: select,
      include-all: true,
      filter: "^(?!.*(?i)(港|hong|hk|台|tai|tw)).*$",
    }

rule-providers:
  Ad:
    type: http
    behavior: classical
    url: "https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical_No_Resolve.yaml"
    interval: 86400
    path: ./ruleset/Advertising_Classical_No_Resolve.yaml
  GlobalMedia:
    type: http
    behavior: classical
    url: "https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical_No_Resolve.yaml"
    interval: 86400
    path: ./ruleset/GlobalMedia_Classical_No_Resolve.yaml
  Global:
    type: http
    behavior: classical
    url: "https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical_No_Resolve.yaml"
    interval: 86400
    path: ./ruleset/Global_Classical_No_Resolve.yaml
  SteamCN:
    type: http
    behavior: classical
    url: "https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN_No_Resolve.yaml"
    interval: 86400
    path: ./ruleset/SteamCN_No_Resolve.yaml
  Steam:
    type: http
    behavior: classical
    url: "https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam_No_Resolve.yaml"
    interval: 86400
    path: ./ruleset/Steam_No_Resolve.yaml
  ChinaMax:
    type: http
    behavior: classical
    url: "https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical_No_Resolve.yaml"
    interval: 86400
    path: ./ruleset/ChinaMax_Classical_No_Resolve.yaml
  Lan:
    type: http
    behavior: classical
    url: "https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan_No_Resolve.yaml"
    interval: 86400
    path: ./ruleset/Lan_No_Resolve.yaml

rules:
  - RULE-SET,Lan,DIRECT
  - RULE-SET,ChinaMax,DIRECT
  - RULE-SET,SteamCN,DIRECT
  - RULE-SET,Steam,PROXY
  - RULE-SET,Global,PROXY
  - RULE-SET,GlobalMedia,PROXY
  - RULE-SET,Ad,AD
  - MATCH,PROXY
